command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "10a878412d504b3d" # Change it to your Warehouse ID
  - name: LLM_MODEL
    value: "databricks-claude-opus-4-6"
